name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.16.0-chrome107-ff107-edge
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Install Firebase Emulator Suite ğŸ”¥
        run: npm install --silent --location=global firebase-tools

      - name: Build For Hosting Emulator ğŸ”¨
        run: npm ci && npm run build

      - name: Cypress ğŸ§ª
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_USERMAIL: ${{ secrets.CYPRESS_USERMAIL }}
          CYPRESS_PASSWORD: '${{ secrets.CYPRESS_PASSWORD }}'
          FIREBASE_TOKEN: '${{secrets.FIREBASE_TOKEN}}'
        with:
          browser: chrome
          start: firebase emulators:exec --token $FIREBASE_TOKEN --project moodify-92f8f 'npm run cypress'
          wait-on: 'http://localhost:3000'
