name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.16.0-chrome107-ff107-edge
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Install Firebase Emulator Suite ğŸ”¥
        run: npm install --silent --location=global firebase-tools

      - name: Build For Hosting Emulator ğŸ”¨
        run: |
          npm install -g tsc
          npm run build

      - name: Cypress ğŸ§ª
        uses: cypress-io/github-action@v5
        env:
          CYPRESS_USERMAIL: ${{ secrets.CYPRESS_USERMAIL }}
          CYPRESS_PASSWORD: '${{ secrets.CYPRESS_PASSWORD }}'
        with:
          browser: chrome
          start: export NODE_ENV=TEST && firebase emulators:exec 'npm run cypress' --project moodify-92f8f
          wait-on: 'http://localhost:3000'
